apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: overkilled-todo
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: todo-key-vault
  target:
    name: db-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: MYSQL_ROOT_PASSWORD
    - secretKey: MYSQL_USER
      remoteRef:
        key: MYSQL_USER
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: MYSQL_PASSWORD
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: MYSQL_DATABASE
