apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delete-service
  template:
    metadata:
      labels:
        app: delete-service
    spec:
      containers:
        - name: delete-service
          image: overkilled-todo-app-delete-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5004
          env:
            - name: DATABASE_HOST
              value: mariadb
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE
            - name: DATABASE_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: delete-service
spec:
  selector:
    app: delete-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004