apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: read-service
  template:
    metadata:
      labels:
        app: read-service
    spec:
      containers:
        - name: read-service
          image: overkilled-todo-app-read-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
          env:
            - name: DATABASE_HOST
              value: mariadb
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE
            - name: DATABASE_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: read-service
spec:
  selector:
    app: read-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002