apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: todo-key-vault
  labels:
    app.kubernetes.io/name: todo-secrets
    app.kubernetes.io/part-of: overkilled-todo
    app.kubernetes.io/managed-by: external-secrets
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://REPLACE_WITH_TERRAFORM_OUTPUT_key_vault_name.vault.azure.net
      serviceAccountRef:
        name: external-secrets
