apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-app
commonAnnotations:
  platform.overkilled.dev/environment: aks-dev
  platform.overkilled.dev/milestone: aks-gitops
resources:
- ../../base
- hpa.yaml
- external-secrets-service-account.yaml
- external-secret-store.yaml
- external-secret.yaml
images:
- name: create-service
  newName: oktododevacr.azurecr.io/overkilled-todo-app-create-service
  newTag: sha-541e24b84c21
- name: delete-service
  newName: oktododevacr.azurecr.io/overkilled-todo-app-delete-service
  newTag: sha-541e24b84c21
- name: read-service
  newName: oktododevacr.azurecr.io/overkilled-todo-app-read-service
  newTag: sha-541e24b84c21
- name: todo-frontend
  newName: oktododevacr.azurecr.io/overkilled-todo-app-todo-frontend
  newTag: sha-541e24b84c21
- name: update-service
  newName: oktododevacr.azurecr.io/overkilled-todo-app-update-service
  newTag: sha-541e24b84c21
replicas:
- count: 2
  name: api-gateway
- count: 2
  name: create-service
- count: 2
  name: delete-service
- count: 2
  name: front-end
- count: 2
  name: read-service
- count: 2
  name: update-service
patches:
- path: patches/ingress.yaml
  target:
    kind: Ingress
    name: todo-ingress
