apiVersion: v1
kind: Namespace
metadata:
  name: policy-system
  labels:
    app.kubernetes.io/name: policy-system
    app.kubernetes.io/part-of: overkilled-todo-platform
    app.kubernetes.io/managed-by: flux
