apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-gateway-manifest.yaml
  - create-service-manifest.yaml
  - database-manifest.yaml
  - delete-service-manifest.yaml
  - front-end-manifest.yaml
  - ingress-manifest.yaml
  - read-service-manifest.yaml
  - update-service-manifest.yaml
